sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
language: elixir
elixir:
    - 1.3.0
otp_release:
    - 19.0
script: "MIX_ENV=test mix do deps.get, deps.compile, conform.effective, release --no-confirm-missing, test --cover"
